/**:
  ros__parameters:

    linear_velocity_factor:
      fast: 1.0
      regular: 0.5
      slow: 0.2

    angular_velocity_factor:
      fast: 1.0
      regular: 0.5
      slow: 0.2

    button_index_map:
      enable_button: 2       # BLUE (X)
      disable_button: 3      # GREEN (A)
      speed_up_button: 1     # YELLOW (Y)
      speed_down_button: 0   # RED (B)

      axis:
        linear_x: 1
        linear_y: 0
